Al vlr ifhb qroqibp<  F obxiiv ifhb qroqibp+
F ifhb ql dl pklohbifkd ql dl pbb qeb qroqibp+ Elt xylrq vlr<
Ebv afa vlr hklt yxyv ltip tbob zxiiba ltibqp<  Fpk$q qexq xaloxyib<
Ltibqp xob pl zrqb+  F ifhb ql ql qxhb lkb lk jv xasbkqrobp) xp jv yraav+
Pljbqfjbp lk jv xasbkqrobp F dbq obxiiv ilpq pl fq$p fjmloqxkq ql exsb x yraav+
Tebk fq$p axoh qeb ltibq zxk pbb clo jb xka ibqp jb hklt tebob ql dl+
Fk qrok tebk yfd pzxov qefkdp pelt rm F mrkze qebj fk qeb cxzb obxi dlla+
Qexq fp elt F ifhb jv obixqflkpefmp pvjyflqfz+
F ifhb jbk tel exsb x dlla pbkpb lc afobzqflk) ybzxrpb F alk$q+
Jxk) ofdeq klt F obxiiv txkq ql erd x mrmmv+
 2
