A device used to display the daily happenings in the land of Vulteria.
A fold-out map of Vulteria and its four main lands.
A rare tome, to be read only by those who desire eternal life and victory.
A small device used to fully sharpen your currently-equipped weapon.
An ancient folk remedy used to fully heal the injured. Black, no sugar.
A very potent form of an ancient healing herb. Battle usage is recommended.
An energy drink developed by wizards for restoring one's magic points.
An electronic device which can tell you a fellow adventurer's location.
An electronic device which can show you a fellow adventurer's location.
A device which can temporarily bring a fellow adventurer to your location.
A precious gem with high non-elemental attack value in battle.
A precious gem with high fire-elemental attack value in battle.
A precious gem with high lightning-elemental attack value in battle.
A precious gem with high ice-elemental attack value in battle.
Headgear worn by priestesses. Can recover 10 HP infinite times during battle.
Headgear worn by demons. Can bring a weaker villain to near-fatal condition.
Headgear which allows for breathing even when submerged in liquids.
Mystic herbs which can resurrect you if they're burning when you die.
A palm-sized piece of metal with the power to dispel curses.
Explosives imbued with magic. Can destroy all evil creatures in a given area.
A device which can return you to the last shrine you visited.
A very long cane with a magnetic tip. Useful for retrieving metal objects.
An oddly-shaped white stone of unknown origins. Possibly used as a key.
An oddly-shaped red stone of unknown origins. Possibly used as a key.
An oddly-shaped blue stone of unknown origins. Possibly used as a key.
A skeleton key. Unlocks all iron doors in Vulteria.
A skeleton key. Unlocks all bronze doors in Vulteria.
A skeleton key. Unlocks all copper doors in Vulteria.
A skeleton key. Unlocks all stone doors in Vulteria.
A device which can descramble a minecar's electronic wheel-lock.
Doug's pride and joy. He'll give you a lot of money for it.
The brown blood of Terrible Tom. Use it to take down a brown barrier.
The yellow blood of Shameless Shiho. Use it to take down a yellow barrier.
The gray blood of Carnie Ken. Use it to take down a gray barrier.
The pink blood of Japanophile Jess. Use it to take down a pink barrier.
The green blood of Jailtime Jimmy. Use it to take down a green barrier.
The flashing (?!) blood of Rowdy Richard. Use it to take down a disco barrier.
The black blood of Cutiepie Kenji. Use it to take down a black barrier.
The cyan blood of Criminally Christine. Use it to take down a cyan barrier.
The white blood of Contagious Kenzo. Use it to take down a white barrier.
The blue blood of JI the JIant. Use it to take down the final blue barrier.
<IGM item>
Only use this if you're ready for a lot of questions. Seriously.
<IGM item>
<IGM item>
Keeps up to 20,000 gold safe and secure, even after being defeated in battle.
An amazing herb/potion mixture which can fully restore all health and magic.
Weapon with virtually no power. Deals 0 to 20 damage. Sticks and stones, eh?
Weapon with the power of Crushing Realism. Deals 20 to 50 damage.
Weapon with the power of Mild Persuasion. Deals 20 to 50 damage.
Weapon with the power of 1337 SKi11z. Deals 20 to 50 damage.
Weapon with the power of Dubious Marketing. Deals 20 to 50 damage.
Weapon with the infinite power of the gods. Deals 40 to 100 damage.
Weapon. Earth-elemental. Deals 20 to 40 damage.
Weapon. Ice/water-elemental. Deals 20 to 40 damage.
Weapon. Lightning-elemental. Deals 20 to 40 damage.
Weapon. Fire-elemental. Deals 20 to 40 damage.
Weapon. No strengths or weaknesses. Deals 30 to 45 damage.
Weapon. Multi-elemental. Deals 50 to 60 damage.
Weapon. No strengths or weaknesses. Deals 20 to 60 damage.
Weapon. Lightning-elemental. Deals 30 to 50 damage.
Weapon. Fire-elemental. Deals 30 to 50 damage.
Weapon. Ice/water-elemental. Deals 30 to 50 damage.
Weapon. Earth-elemental. Deals 30 to 50 damage.
Weapon. No strengths or weaknesses. Deals 0 to 75 damage.
Weapon. No strengths or weaknesses. Deals 60 damage.
Weapon. Random elemental (varies). Deals up to 100 damage.
Armor with no strengths or weaknesses, but offers only 5% protection.
Armor. Blocks skill, but is weak to persuasion. Offers 15% protection.
Armor. Blocks persuasion, but is weak to skill. Offers 15% protection.
Armor. Blocks realism, but is weak to marketing. Offers 15% protection.
Armor. Blocks marketing, but is weak to realism. Offers 15% protection.
The greatest armor of them all. Offers 90% protection. We love you guys!
Armor. Does not block earth well. Absorbs 25% of damage.
Armor. Blocks fire well, but not ice/water. Absorbs 20% of damage.
Armor. Blocks ice/water well, but not fire. Absorbs 20% of damage.
Armor. Blocks ice/water well, but not earth. Absorbs 20% of damage.
Armor. Blocks earth well. Absorbs 50% of damage.
Armor. No strengths or weaknesses. Absorbs 75% of damage.
Armor. Weaknesses vary. Absorbs 90% of damage.
