A device used to display the daily happenings in the land of Vulteria.
A fold-out map of Vulteria and its four main lands.
A rare tome, to be read only by those who desire eternal life and victory.
A small device used to fully sharpen your currently-equipped weapon.
An ancient folk remedy used to fully heal the sick and injured.
A very potent form of an ancient healing herb. Battle usage is recommended.
A concoction developed by wizards for restoring one's magic points.
An electronic device which can tell you a fellow adventurer's location.
An electronic device which can show you a fellow adventurer's location.
A device which can temporarily bring a fellow adventurer to your location.
A precious gem with high non-elemental attack value in battle.
A precious gem with high fire-elemental attack value in battle.
A precious gem with high lightning-elemental attack value in battle.
A precious gem with high ice-elemental attack value in battle.
Headgear worn by priestesses. Can recover 10 HP infinite times during battle.
Headgear worn by demons. Can bring a weaker villain to near-fatal condition.
Headgear which allows for breathing even when submerged in liquids.
Mystic herbs which can resurrect you if they're burning when you die.
A palm-sized piece of metal with the power to dispel curses.
Explosives imbued with magic. Can destroy all evil creatures in a given area.
A device which can return you to the last shrine you visited.
A very long cane with a magnetic tip. Useful for retrieving metal objects.
An oddly-shaped white stone of unknown origins. Possibly used as a key.
An oddly-shaped red stone of unknown origins. Possibly used as a key.
An oddly-shaped blue stone of unknown origins. Possibly used as a key.
A skeleton key. Unlocks all iron doors in Vulteria.
A skeleton key. Unlocks all bronze doors in Vulteria.
A skeleton key. Unlocks all copper doors in Vulteria.
A skeleton key. Unlocks all stone doors in Vulteria.
A device which can descramble a minecar's electronic wheel-lock.
Doug's pride and joy. He'll give you a lot of money for it.
A lightning-elemental gem which can destroy a corresponding barrier.
A fire-elemental gem which can destroy a corresponding barrier.
An ice-elemental gem which can destroy a corresponding barrier.
An earth-elemental gem which can destroy a corresponding barrier.
Permanently teaches you four attack spells and increases your evade% by 5.
Permanently teaches you four recovery spells and increases your evade% by 5.
Ensures you never forget all the spells you currently know.
A vial of the evil shapechanger's blood. Increases your evade% by 10.
<IGM item>
<IGM item>
<IGM item>
Only use this if you're ready for a lot of questions. Seriously.
<IGM item>
<IGM item>
Keeps up to 20,000 gold safe and secure, even after being defeated in battle.
An amazing herb/potion mixture which can fully restore all health and magic.
Weapon. No strengths or weaknesses. Deals 0 to 10 damage.
Weapon. No strengths or weaknesses. Deals 5 to 12 damage.
Weapon. No strengths or weaknesses. Deals 8 to 15 damage.
Weapon. No strengths or weaknesses. Deals 10 to 20 damage.
Weapon. No strengths or weaknesses. Deals 10 to 30 damage.
Weapon. No strengths or weaknesses. Deals 15 to 25 damage.
Weapon. Earth-elemental. Deals 20 to 40 damage.
Weapon. Ice/water-elemental. Deals 20 to 40 damage.
Weapon. Lightning-elemental. Deals 20 to 40 damage.
Weapon. Fire-elemental. Deals 20 to 40 damage.
Weapon. No strengths or weaknesses. Deals 30 to 45 damage.
Weapon. Multi-elemental. Deals 50 to 60 damage.
Weapon. No strengths or weaknesses. Deals 20 to 60 damage.
Weapon. Lightning-elemental. Deals 30 to 50 damage.
Weapon. Fire-elemental. Deals 30 to 50 damage.
Weapon. Ice/water-elemental. Deals 30 to 50 damage.
Weapon. Earth-elemental. Deals 30 to 50 damage.
Weapon. No strengths or weaknesses. Deals 0 to 75 damage.
Weapon. No strengths or weaknesses. Deals 60 damage.
Weapon. Random elemental (varies). Deals up to 100 damage.
Armor. No strengths or weaknesses. Absorbs 5% of damage.
Armor. No strengths or weaknesses. Absorbs 10% of damage.
Armor. Blocks earth well, but not lightning. Absorbs 10% of damage.
Armor. Blocks lightning well, but not ice/water. Absorbs 20% of damage.
Armor. Blocks all elementals, but offers no protection against attacks.
Armor. No strengths or weaknesses. Absorbs 20% of damage.
Armor. Does not block earth well. Absorbs 25% of damage.
Armor. Blocks fire well, but not ice/water. Absorbs 20% of damage.
Armor. Blocks ice/water well, but not fire. Absorbs 20% of damage.
Armor. Blocks ice/water well, but not earth. Absorbs 20% of damage.
Armor. Blocks earth well. Absorbs 50% of damage.
Armor. No strengths or weaknesses. Absorbs 75% of damage.
Armor. Weaknesses vary. Absorbs 90% of damage.
